 # NYC Trip Fare

In [198]:
pip install skimpy

Collecting skimpy
  Using cached skimpy-0.0.18-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: click>=8.1.7 in /opt/anaconda3/lib/python3.12/site-packages (from skimpy) (8.1.7)
Collecting ipykernel>=6.29.5 (from skimpy)
  Using cached ipykernel-6.29.5-py3-none-any.whl.metadata (6.3 kB)
Collecting numpy>=2.0.2 (from skimpy)
  Using cached numpy-2.2.1-cp312-cp312-macosx_10_13_x86_64.whl.metadata (62 kB)
Collecting pandas-stubs>=2.2.2.240807 (from skimpy)
  Using cached pandas_stubs-2.2.3.241126-py3-none-any.whl.metadata (10.0 kB)
Collecting pandas>=2.2.3 (from skimpy)
  Using cached pandas-2.2.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata (89 kB)
Collecting polars>=1.17.1 (from skimpy)
  Using cached polars-1.19.0-cp39-abi3-macosx_10_12_x86_64.whl.metadata (14 kB)
Collecting pygments>=2.18.0 (from skimpy)
  Using cached pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting rich>=13.9.4 (from skimpy)
  Using cached rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting typeguard>=4.4.1 (from skimpy)
  Using cached typeguard-4.4.1-py3-none-any.whl.metadata (3.7 kB)
Collecting pyarrow>=17.0.0 (from skimpy)
  Using cached pyarrow-18.1.0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: appnope in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (0.1.3)
Requirement already satisfied: comm>=0.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (8.25.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (0.1.6)
Requirement already satisfied: nest-asyncio in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (1.6.0)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (23.2)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (5.9.0)
Requirement already satisfied: pyzmq>=24 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (25.1.2)
Requirement already satisfied: tornado>=6.1 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from ipykernel>=6.29.5->skimpy) (5.14.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=2.2.3->skimpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=2.2.3->skimpy) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=2.2.3->skimpy) (2023.3)
Collecting types-pytz>=2022.1.1 (from pandas-stubs>=2.2.2.240807->skimpy)
  Using cached types_pytz-2024.2.0.20241221-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich>=13.9.4->skimpy) (2.2.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from typeguard>=4.4.1->skimpy) (4.11.0)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.18.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (3.0.43)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.12/site-packages (from ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (4.8.0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=6.29.5->skimpy) (3.10.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.9.4->skimpy) (0.1.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->skimpy) (1.16.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/anaconda3/lib/python3.12/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.12/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.7.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.2.5)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.8.3)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (2.0.5)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=6.29.5->skimpy) (0.2.2)
Using cached skimpy-0.0.18-py3-none-any.whl (17 kB)
Using cached ipykernel-6.29.5-py3-none-any.whl (117 kB)
Using cached numpy-2.2.1-cp312-cp312-macosx_10_13_x86_64.whl (20.9 MB)
Using cached pandas-2.2.3-cp312-cp312-macosx_10_9_x86_64.whl (12.5 MB)
Using cached pandas_stubs-2.2.3.241126-py3-none-any.whl (158 kB)
Using cached polars-1.19.0-cp39-abi3-macosx_10_12_x86_64.whl (29.5 MB)
Using cached pygments-2.19.1-py3-none-any.whl (1.2 MB)
Using cached rich-13.9.4-py3-none-any.whl (242 kB)
Using cached typeguard-4.4.1-py3-none-any.whl (35 kB)
Using cached types_pytz-2024.2.0.20241221-py3-none-any.whl (10 kB)
Building wheels for collected packages: pyarrow
  Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyarrow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [784 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/orc.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/conftest.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/_generated_version.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/benchmark.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/_compute_docstrings.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/ipc.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/util.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/flight.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/cffi.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/substrait.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/types.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/dataset.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/cuda.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/feather.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/pandas_compat.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/fs.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/acero.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/csv.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/jvm.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/json.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      copying pyarrow/compute.py -> build/lib.macosx-10.15-x86_64-cpython-312/pyarrow
      running egg_info
      writing pyarrow.egg-info/PKG-INFO
      writing dependency_links to pyarrow.egg-info/dependency_links.txt
      writing requirements to pyarrow.egg-info/requires.txt
      writing top-level names to pyarrow.egg-info/top_level.txt
      ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
      reading manifest file 'pyarrow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '../LICENSE.txt'
      warning: no files found matching '../NOTICE.txt'
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*~' found anywhere in distribution
      warning: no previously-included files matching '#*' found anywhere in distribution
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '.DS_Store' found anywhere in distribution
      no previously-included directories found matching '.asv'
      writing manifest file 'pyarrow.egg-info/SOURCES.txt'
      /private/var/folders/r6/c6yvzsx90hs9_nxx95165twc0000gn/T/pip-build-env-7pnz6en8/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'pyarrow.includes' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'pyarrow.includes' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'pyarrow.includes' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'pyarrow.includes' to be distributed and are
              already explicitly excluding 'pyarrow.includes' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      /private/var/folders/r6/c6yvzsx90hs9_nxx95165twc0000gn/T/pip-build-env-7pnz6en8/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'pyarrow.interchange' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'pyarrow.interchange' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'pyarrow.interchange' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'pyarrow.interchange' to be distributed and are
              already explicitly excluding 'pyarrow.interchange' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      /private/var/folders/r6/c6yvzsx90hs9_nxx95165twc0000gn/T/pip-build-env-7pnz6en8/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'pyarrow.parquet' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'pyarrow.parquet' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'pyarrow.parquet' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'pyarrow.parquet' to be distributed and are
              already explicitly excluding 'pyarrow.parquet' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      /private/var/folders/r6/c6yvzsx90hs9_nxx95165twc0000gn/T/pip-build-env-7pnz6en8/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'pyarrow.src.arrow.python' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'pyarrow.src.arrow.python' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'pyarrow.src.arrow.python' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'pyarrow.src.arrow.python' to be distributed and are
              already explicitly excluding 'pyarrow.src.arrow.python' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html


              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      /private/var/folders/r6/c6yvzsx90hs9_nxx95165twc0000gn/T/pip-build-env-7pnz6en8/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:212: _Warning: Package 'pyarrow.src.arrow.python.vendored' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################

In [199]:
import pandas as pd
from datetime import timedelta
from skimpy import skim

ModuleNotFoundError: No module named 'skimpy'

In [201]:
# to avoid the dtype error for store_and_fwd_flag column we set the type of the variable to category
NYC = pd.read_csv("/Users/federicaromano/Desktop/università/1_Foundations of Computer Science/0PROGETTO/data.csv", 
                  dtype = {'store_and_fwd_flag': 'category'})
NYC.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.2,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.2,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.6,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.8,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.0,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0

In [202]:
#Format='mixed' attempts to automatically infer the date format for each element individually within the column. 
# It was not risky to use this command because the date formats were not ambiguous. 
NYC['tpep_pickup_datetime'] = pd.to_datetime(NYC['tpep_pickup_datetime'], format ='mixed')
NYC['tpep_dropoff_datetime'] = pd.to_datetime(NYC['tpep_dropoff_datetime'], format ='mixed')

In [ ]:
skim(NYC)

In [203]:
# We remove the rows with negative distances
neg_dist=NYC[NYC['trip_distance']<0]
NYC=NYC.drop(neg_dist.index)
NYC.reset_index()

,index,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.00,3.00,0.5,1.47,0.00,0.3,11.27,2.5
1,1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.00,3.00,0.5,1.50,0.00,0.3,12.30,2.5
2,2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.00,3.00,0.5,1.00,0.00,0.3,10.80,2.5
3,3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.50,0.50,0.5,1.36,0.00,0.3,8.16,0.0
4,4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.50,0.50,0.5,0.00,0.00,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6402665,6405003,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.24,NaN,NaN,237,234,NaN,17.59,2.75,0.5,0.00,0.00,0.3,21.14,0.0
6402666,6405004,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.13,NaN,NaN,259,45,NaN,46.67,2.75,0.5,0.00,12.24,0.3,62.46,0.0
6402667,6405005,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.51,NaN,NaN,137,169,NaN,48.85,2.75,0.0,0.00,0.00,0.3,51.90,0.0
6402668,6405006,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.49,NaN,NaN,50,42,NaN,27.17,2.75,0.0,0.00,0.00,0.3,30.22,0.0
6402669,6405007,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.60,NaN,NaN,179,205,NaN,54.56,2.75,0.5,0.00,0.00,0.3,58.11,0.0

In [204]:
# We noticed that in some rows all the attributes relative to payments were negative so 
# at first we saved the indexes of those rows
negative_rows = NYC[NYC['fare_amount'] < 0]
modified_indices = negative_rows.index.tolist()

# Then all the negative values are transformed into positive 
NYC.loc[modified_indices] = NYC.loc[modified_indices].map(
    lambda x: abs(x) if isinstance(x, (int, float)) else x
)

# Here we searched for duplicates (ie couple of rows that could refer to cancelled trips)
duplicated_rows = NYC[NYC.duplicated(keep=False)]
NYC = NYC.drop(duplicated_rows.index)

# In the end we remove the remaining negative rows
remaining_indices = set(modified_indices) - set(duplicated_rows.index)
NYC = NYC.drop(remaining_indices) 
NYC

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.00,3.00,0.5,1.47,0.00,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.00,3.00,0.5,1.50,0.00,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.00,3.00,0.5,1.00,0.00,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.50,0.50,0.5,1.36,0.00,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.50,0.50,0.5,0.00,0.00,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405003,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.24,NaN,NaN,237,234,NaN,17.59,2.75,0.5,0.00,0.00,0.3,21.14,0.0
6405004,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.13,NaN,NaN,259,45,NaN,46.67,2.75,0.5,0.00,12.24,0.3,62.46,0.0
6405005,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.51,NaN,NaN,137,169,NaN,48.85,2.75,0.0,0.00,0.00,0.3,51.90,0.0
6405006,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.49,NaN,NaN,50,42,NaN,27.17,2.75,0.0,0.00,0.00,0.3,30.22,0.0
6405007,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.60,NaN,NaN,179,205,NaN,54.56,2.75,0.5,0.00,0.00,0.3,58.11,0.0

## 1.Extract all trips with trip_distance larger than 50

In [207]:
larger_trip = NYC[NYC['trip_distance'] > 50]
larger_trip

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
23842,2.0,2020-01-01 01:53:07,2020-01-01 03:54:41,1.0,52.30,5.0,N,262,265,1.0,300.00,0.00,0.0,61.78,6.12,0.3,370.70,2.5
39013,2.0,2020-01-01 02:05:07,2020-01-01 03:03:10,1.0,51.23,5.0,N,264,264,1.0,329.00,0.00,0.5,100.78,6.12,0.3,436.70,0.0
41620,1.0,2020-01-01 03:05:54,2020-01-01 04:16:26,1.0,53.80,5.0,N,132,265,1.0,250.00,0.00,0.0,53.35,16.62,0.3,320.27,0.0
58262,2.0,2020-01-01 05:36:12,2020-01-01 06:40:06,1.0,55.23,5.0,N,132,265,2.0,170.00,0.00,0.5,0.00,18.26,0.3,189.06,0.0
63024,2.0,2020-01-01 07:40:30,2020-01-01 08:40:01,1.0,54.19,5.0,N,132,265,1.0,230.00,0.00,0.0,0.00,12.24,0.3,242.54,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6326169,2.0,2020-01-31 22:47:26,2020-01-31 23:49:14,1.0,51.83,5.0,N,132,265,1.0,220.00,0.00,0.5,48.96,23.99,0.3,293.75,0.0
6331181,2.0,2020-01-31 23:45:36,2020-02-01 01:00:25,5.0,57.99,4.0,N,107,265,1.0,245.00,0.50,0.5,38.24,6.12,0.3,293.16,2.5
6333801,2.0,2020-01-31 23:24:16,2020-02-01 01:32:56,1.0,52.97,4.0,N,264,265,1.0,227.00,0.50,0.5,46.16,0.00,0.3,276.96,2.5
6397132,NaN,2020-01-28 11:54:00,2020-01-28 19:35:00,NaN,60.36,NaN,NaN,17,61,NaN,12.04,0.00,0.5,0.00,12.24,0.3,25.08,0.0
6398446,NaN,2020-01-28 07:37:00,2020-01-28 08:42:00,NaN,210240.07,NaN,NaN,76,231,NaN,37.77,2.75,0.5,0.00,0.00,0.3,41.32,0.0

## 2.Extract all trips where payment_type is missing

In [209]:
# For each row we check if the payment type is missing
no_payment = NYC[NYC['payment_type'].isna()]
no_payment

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
6339567,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.69,NaN,NaN,136,232,NaN,51.05,2.75,0.5,0.0,0.00,0.3,54.60,0.0
6339568,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.42,NaN,NaN,121,9,NaN,27.06,2.75,0.0,0.0,0.00,0.3,30.11,0.0
6339569,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.20,NaN,NaN,197,216,NaN,24.36,2.75,0.5,0.0,0.00,0.3,27.91,0.0
6339570,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.84,NaN,NaN,262,236,NaN,26.08,2.75,0.5,0.0,0.00,0.3,29.63,0.0
6339571,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.24,NaN,NaN,45,142,NaN,25.28,2.75,0.5,0.0,0.00,0.3,28.83,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405003,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.24,NaN,NaN,237,234,NaN,17.59,2.75,0.5,0.0,0.00,0.3,21.14,0.0
6405004,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.13,NaN,NaN,259,45,NaN,46.67,2.75,0.5,0.0,12.24,0.3,62.46,0.0
6405005,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.51,NaN,NaN,137,169,NaN,48.85,2.75,0.0,0.0,0.00,0.3,51.90,0.0
6405006,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.49,NaN,NaN,50,42,NaN,27.17,2.75,0.0,0.0,0.00,0.3,30.22,0.0
6405007,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.60,NaN,NaN,179,205,NaN,54.56,2.75,0.5,0.0,0.00,0.3,58.11,0.0

## 3.For each (PULocationID, DOLocationID) pair, determine the number of trips

In [212]:
# We used groupby to make the PU,DO location pairs and then used size to determine the number of trips related 
n_trips = NYC.groupby(['PULocationID', 'DOLocationID']).size().reset_index(name='n_trips')
n_trips=n_trips.sort_values(['PULocationID', 'DOLocationID'])
n_trips

       PULocationID  DOLocationID  n_trips
0                 1             1      629
1                 1            50        1
2                 1            68        1
3                 1           138        2
4                 1           140        1
...             ...           ...      ...
30356           265           259        1
30357           265           261        1
30358           265           263        4
30359           265           264      313
30360           265           265     2453

[30361 rows x 3 columns]

## 4.Save all rows with missing VendorID, passenger_count, store_and_fwd_flag, payment_type in a new dataframe called bad, and remove those rows from the original dataframe.

In [227]:
# All rows having at least one missing values in one of these columns 
#(VendorID, passenger_count, store_and_fwd_flag, payment_type) are selected
bad = NYC[NYC[['VendorID', 'passenger_count', 'store_and_fwd_flag', 'payment_type']].isna().any(axis=1)]
bad

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
6339567,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.69,NaN,NaN,136,232,NaN,51.05,2.75,0.5,0.0,0.00,0.3,54.60,0.0
6339568,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.42,NaN,NaN,121,9,NaN,27.06,2.75,0.0,0.0,0.00,0.3,30.11,0.0
6339569,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.20,NaN,NaN,197,216,NaN,24.36,2.75,0.5,0.0,0.00,0.3,27.91,0.0
6339570,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.84,NaN,NaN,262,236,NaN,26.08,2.75,0.5,0.0,0.00,0.3,29.63,0.0
6339571,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.24,NaN,NaN,45,142,NaN,25.28,2.75,0.5,0.0,0.00,0.3,28.83,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405003,NaN,2020-01-31 22:51:00,2020-01-31 23:22:00,NaN,3.24,NaN,NaN,237,234,NaN,17.59,2.75,0.5,0.0,0.00,0.3,21.14,0.0
6405004,NaN,2020-01-31 22:10:00,2020-01-31 23:26:00,NaN,22.13,NaN,NaN,259,45,NaN,46.67,2.75,0.5,0.0,12.24,0.3,62.46,0.0
6405005,NaN,2020-01-31 22:50:07,2020-01-31 23:17:57,NaN,10.51,NaN,NaN,137,169,NaN,48.85,2.75,0.0,0.0,0.00,0.3,51.90,0.0
6405006,NaN,2020-01-31 22:25:53,2020-01-31 22:48:32,NaN,5.49,NaN,NaN,50,42,NaN,27.17,2.75,0.0,0.0,0.00,0.3,30.22,0.0
6405007,NaN,2020-01-31 22:44:00,2020-01-31 23:06:00,NaN,11.60,NaN,NaN,179,205,NaN,54.56,2.75,0.5,0.0,0.00,0.3,58.11,0.0

In [216]:
# We removed the "bad" rows from the original dataset to create a new one with no NaN
NYC_nona = NYC.drop(bad.index)
NYC_nona.reset_index()
NYC_nona

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6339562,2.0,2020-01-31 23:38:07,2020-01-31 23:52:21,1.0,2.10,1.0,N,163,246,1.0,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5
6339563,2.0,2020-01-31 23:00:18,2020-01-31 23:19:18,1.0,2.13,1.0,N,164,79,1.0,13.0,0.5,0.5,3.36,0.0,0.3,20.16,2.5
6339564,2.0,2020-01-31 23:24:22,2020-01-31 23:40:39,1.0,2.55,1.0,N,79,68,1.0,12.5,0.5,0.5,3.26,0.0,0.3,19.56,2.5
6339565,2.0,2020-01-31 23:44:22,2020-01-31 23:54:00,1.0,1.61,1.0,N,100,142,2.0,8.5,0.5,0.5,0.00,0.0,0.3,12.30,2.5
6339566,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,1.0,0.00,1.0,N,193,193,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0

## 5.Add a duration column storing how long each trip has taken (use tpep_pickup_datetime, tpep_dropoff_datetime)

In [229]:
# We subtracted the pick-up time from the drop-off time to calculate the duration of each trip
NYC_nona['duration'] = (NYC_nona['tpep_dropoff_datetime'] - NYC_nona['tpep_pickup_datetime'])
NYC_nona

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,duration
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5,0 days 00:04:48
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5,0 days 00:07:25
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5,0 days 00:06:11
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0,0 days 00:04:51
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0,0 days 00:02:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6339562,2.0,2020-01-31 23:38:07,2020-01-31 23:52:21,1.0,2.10,1.0,N,163,246,1.0,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5,0 days 00:14:14
6339563,2.0,2020-01-31 23:00:18,2020-01-31 23:19:18,1.0,2.13,1.0,N,164,79,1.0,13.0,0.5,0.5,3.36,0.0,0.3,20.16,2.5,0 days 00:19:00
6339564,2.0,2020-01-31 23:24:22,2020-01-31 23:40:39,1.0,2.55,1.0,N,79,68,1.0,12.5,0.5,0.5,3.26,0.0,0.3,19.56,2.5,0 days 00:16:17
6339565,2.0,2020-01-31 23:44:22,2020-01-31 23:54:00,1.0,1.61,1.0,N,100,142,2.0,8.5,0.5,0.5,0.00,0.0,0.3,12.30,2.5,0 days 00:09:38
6339566,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,1.0,0.00,1.0,N,193,193,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0 days 00:01:04

In [231]:
# Checking if there are some rows where DO_datetime is before PU_datetime 
err_duration = NYC_nona[NYC_nona['duration'] <timedelta(0)]
# Removing inconsistencies 
NYC_nona=NYC_nona.drop(err_duration.index)
NYC_nona.reset_index()

,index,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,duration
0,0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5,0 days 00:04:48
1,1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5,0 days 00:07:25
2,2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5,0 days 00:06:11
3,3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0,0 days 00:04:51
4,4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0,0 days 00:02:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6317062,6339562,2.0,2020-01-31 23:38:07,2020-01-31 23:52:21,1.0,2.10,1.0,N,163,246,1.0,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5,0 days 00:14:14
6317063,6339563,2.0,2020-01-31 23:00:18,2020-01-31 23:19:18,1.0,2.13,1.0,N,164,79,1.0,13.0,0.5,0.5,3.36,0.0,0.3,20.16,2.5,0 days 00:19:00
6317064,6339564,2.0,2020-01-31 23:24:22,2020-01-31 23:40:39,1.0,2.55,1.0,N,79,68,1.0,12.5,0.5,0.5,3.26,0.0,0.3,19.56,2.5,0 days 00:16:17
6317065,6339565,2.0,2020-01-31 23:44:22,2020-01-31 23:54:00,1.0,1.61,1.0,N,100,142,2.0,8.5,0.5,0.5,0.00,0.0,0.3,12.30,2.5,0 days 00:09:38
6317066,6339566,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,1.0,0.00,1.0,N,193,193,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0 days 00:01:04

## 6.For each pickup location, determine how many trips have started there.

In [233]:
# We grouped by PU location and then used size to determine the number of trips started there 
n_started = NYC_nona.groupby('PULocationID').size().rename('n_started').to_frame()
n_started

              n_started
PULocationID
1                   746
2                     3
3                    70
4                  9850
5                    39
...                 ...
261               34088
262               85375
263              123594
264               43383
265                3041

[260 rows x 1 columns]

## 7.Cluster the pickup time of the day into 30-minute intervals (e.g. from 02:00 to 02:30)

In [237]:
# We rounded every pickup time to the previous half-hour
NYC_nona['clustered_pu_time'] = pd.to_datetime(NYC_nona['tpep_pickup_datetime']).dt.floor('30min').dt.time
NYC_nona[['tpep_pickup_datetime','clustered_pu_time']].sort_values('clustered_pu_time')

        tpep_pickup_datetime clustered_pu_time
0        2020-01-01 00:28:15          00:00:00
2930202  2020-01-16 00:06:17          00:00:00
2930203  2020-01-16 00:01:00          00:00:00
2930204  2020-01-16 00:07:54          00:00:00
2930206  2020-01-16 00:28:29          00:00:00
...                      ...               ...
1668288  2020-01-09 23:52:32          23:30:00
1668330  2020-01-09 23:53:55          23:30:00
1668363  2020-01-09 23:58:23          23:30:00
1667760  2020-01-09 23:51:05          23:30:00
10820    2019-12-31 23:53:57          23:30:00

[6317067 rows x 2 columns]

## 8.For each interval, determine the average number of passengers and the average fare amount.

In [239]:
# We grouped by PU time interval and then used mean to compute the average of number of passengers and fare amount
intervals = NYC_nona.groupby('clustered_pu_time')[['passenger_count', 'fare_amount']].mean().rename(
    columns={'passenger_count': 'average passenger count', 'fare_amount': 'average fare amount'})
intervals

                   average passenger count  average fare amount
clustered_pu_time
00:00:00                          1.573773            13.636197
00:30:00                          1.585621            13.333230
01:00:00                          1.580176            12.827484
01:30:00                          1.590201            12.393858
02:00:00                          1.588002            12.220783
02:30:00                          1.588507            12.203625
03:00:00                          1.584083            12.697753
03:30:00                          1.587730            13.296441
04:00:00                          1.581479            14.427337
04:30:00                          1.516719            16.660893
05:00:00                          1.484131            18.856942
05:30:00                          1.414710            15.809831
06:00:00                          1.393911            14.679081
06:30:00                          1.384014            12.383363
07:00:00                          1.415624            12.320844
07:30:00                          1.449668            11.825271
08:00:00                          1.459013            12.005822
08:30:00                          1.444150            11.919552
09:00:00                          1.453436            12.127732
09:30:00                          1.469708            11.941123
10:00:00                          1.487036            12.115713
10:30:00                          1.494430            11.907092
11:00:00                          1.502521            11.954778
11:30:00                          1.500890            11.706480
12:00:00                          1.499839            11.970264
12:30:00                          1.498999            12.043683
13:00:00                          1.506874            12.436222
13:30:00                          1.514222            12.639337
14:00:00                          1.512129            13.052314
14:30:00                          1.509395            12.854004
15:00:00                          1.525696            12.958056
15:30:00                          1.522368            12.959867
16:00:00                          1.516212            13.362895
16:30:00                          1.513168            13.017204
17:00:00                          1.514479            12.759459
17:30:00                          1.523610            12.292455
18:00:00                          1.518486            12.216133
18:30:00                          1.525733            11.971935
19:00:00                          1.525630            11.944635
19:30:00                          1.529528            12.071462
20:00:00                          1.530529            12.575302
20:30:00                          1.539943            12.779678
21:00:00                          1.552240            12.811372
21:30:00                          1.565049            12.628086
22:00:00                          1.566182            12.878739
22:30:00                          1.571915            13.250204
23:00:00                          1.569432            13.343044
23:30:00                          1.570935            13.305134

## 9.For each payment type and each interval, determine the average fare amount

In [243]:
# We grouped by payment type and PU time interval and then used mean to compute the average of the fare amount
payments_intervals = NYC_nona.groupby(['payment_type','clustered_pu_time'])['fare_amount'].mean().reset_index().rename(
    columns={'fare_amount': 'average fare amount'})
payments_intervals

     payment_type clustered_pu_time  average fare amount
0             1.0          00:00:00            13.869142
1             1.0          00:30:00            13.472705
2             1.0          01:00:00            12.824603
3             1.0          01:30:00            12.357974
4             1.0          02:00:00            12.008589
..            ...               ...                  ...
188           4.0          22:00:00            13.521681
189           4.0          22:30:00            15.444021
190           4.0          23:00:00            13.995263
191           4.0          23:30:00            14.499497
192           5.0          17:30:00             0.000000

[193 rows x 3 columns]

## 10.For each payment type, determine the interval when the average fare amount is maximum

In [245]:
# Using the table computed in the previous point, we extracted the maximum average fare amount with idxmax 
# for each payment type (group by) and then located it with .loc
max_avg_fare = payments_intervals.loc[payments_intervals.groupby('payment_type')['average fare amount'].idxmax()]
max_avg_fare

     payment_type clustered_pu_time  average fare amount
10            1.0          05:00:00            21.256949
58            2.0          05:00:00            14.944475
105           3.0          04:30:00            16.555657
154           4.0          05:00:00            24.230667
192           5.0          17:30:00             0.000000

## 11.For each payment type, determine the interval when the overall ratio between the tip and the fare amounts is maximum

In [247]:
# We used groupby to make the payment type, PU time interval pairs and then computed the sum of tip and fare amount
overall_ratio = NYC_nona.groupby(['payment_type', 'clustered_pu_time']).agg(
    total_tip_amount=('tip_amount', 'sum'),
    total_fare_amount=('fare_amount', 'sum')).reset_index()

# We computed the overall ratio
overall_ratio['overall_ratio'] = overall_ratio['total_tip_amount'] / overall_ratio['total_fare_amount']

# From the previous point, we noticed that for the payment type 5 all the payments were 0 so the ratio result is null
# To allow .idxmax() to work, we removed this result
overall_ratio = overall_ratio[overall_ratio['overall_ratio'].notnull()]

# We extracted the maximum overall ratio with idxmax 
# for each payment type (group by) and then located it with .loc
max_overall_ratio = overall_ratio.loc[overall_ratio.groupby('payment_type')['overall_ratio'].idxmax()]

max_overall_ratio

,payment_type,clustered_pu_time,total_tip_amount,total_fare_amount,overall_ratio
37,1.0,18:30:00,485539.83,1998339.28,0.242972
68,2.0,10:00:00,22.88,453651.77,0.000050
138,3.0,21:00:00,41.65,7623.82,0.005463
164,4.0,10:00:00,3.95,2088.02,0.001892

## 12.Find the location with the highest average fare amount

In [249]:
# For each PU location we compute the average fare amount
max_loc = NYC_nona.groupby('PULocationID')['fare_amount'].mean()

# We extract the index of the PU location with the maximum average fare amount
max_pulocation_id = max_loc.idxmax() 

# We extract the maximum average fare amount for that location
max_fare_amount = max_loc.max() 
print(f"PULocationID: {max_pulocation_id}, Highest Mean Fare Amount: {max_fare_amount}")

PULocationID: 204, Highest Mean Fare Amount: 107.0

## 13.Build a new dataframe (called common) where, for each pickup location we keep all trips to the 5 most common destinations (i.e. each pickup location can have different common destinations).

In [253]:
# We grouped by pickup and drop-off locations and counted occurrences
sum_dest = NYC_nona.groupby(['PULocationID', 'DOLocationID']).size().reset_index(name='count')

# For each PU location we computed the 5 most frequent DO locations
top5dest = (sum_dest.sort_values(by=['PULocationID', 'count'], ascending=[True, False])
            .groupby('PULocationID').head(5).reset_index(drop=True))
top5dest

      PULocationID  DOLocationID  count
0                1             1    629
1                1           264    105
2                1           265      4
3                1           138      2
4                1            50      1
...            ...           ...    ...
1255           265           265   2451
1256           265           264    313
1257           265             1     76
1258           265            48     18
1259           265           132      8

[1260 rows x 3 columns]

In [255]:
# We created a new dataframe containing only the trips having PU,DO location pair in the top5dest table
common = NYC_nona.merge(top5dest[['PULocationID', 'DOLocationID']], on=['PULocationID', 'DOLocationID'], how='inner')
common

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,duration,clustered_pu_time
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,1.0,1.20,1.0,N,238,239,1.0,6.0,3.0,0.5,1.47,0.0,0.3,11.27,2.5,0 days 00:04:48,00:00:00
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,1.0,1.20,1.0,N,239,238,1.0,7.0,3.0,0.5,1.50,0.0,0.3,12.30,2.5,0 days 00:07:25,00:30:00
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,1.0,0.60,1.0,N,238,238,1.0,6.0,3.0,0.5,1.00,0.0,0.3,10.80,2.5,0 days 00:06:11,00:30:00
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,1.0,0.80,1.0,N,238,151,1.0,5.5,0.5,0.5,1.36,0.0,0.3,8.16,0.0,0 days 00:04:51,00:30:00
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,1.0,0.00,1.0,N,193,193,2.0,3.5,0.5,0.5,0.00,0.0,0.3,4.80,0.0,0 days 00:02:18,00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1945362,2.0,2020-02-01 00:00:37,2020-02-01 00:11:59,1.0,1.18,1.0,N,186,170,1.0,8.5,0.5,0.5,2.46,0.0,0.3,14.76,2.5,0 days 00:11:22,00:00:00
1945363,2.0,2020-01-31 22:59:01,2020-01-31 23:06:15,3.0,0.90,1.0,N,238,239,2.0,6.5,0.5,0.5,0.00,0.0,0.3,10.30,2.5,0 days 00:07:14,22:30:00
1945364,2.0,2020-01-31 23:44:34,2020-01-31 23:47:46,3.0,0.80,1.0,N,141,141,2.0,4.5,0.5,0.5,0.00,0.0,0.3,8.30,2.5,0 days 00:03:12,23:30:00
1945365,2.0,2020-01-31 23:01:38,2020-01-31 23:05:49,1.0,0.74,1.0,N,48,142,1.0,5.0,0.5,0.5,1.76,0.0,0.3,10.56,2.5,0 days 00:04:11,23:00:00
1945366,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,1.0,0.00,1.0,N,193,193,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0 days 00:01:04,23:00:00

## 14.On the common dataframe, for each payment type and each interval, determine the average fare amount

In [259]:
# We grouped by payment type and PU time interval and then used mean to compute the average of the fare amount
common_pay_int = common.groupby(['payment_type','clustered_pu_time'])['fare_amount'].mean().reset_index().rename(
    columns={'fare_amount': 'average fare amount 2'})
common_pay_int

     payment_type clustered_pu_time  average fare amount 2
0             1.0          00:00:00               8.543145
1             1.0          00:30:00               8.635086
2             1.0          01:00:00               8.475573
3             1.0          01:30:00               7.963448
4             1.0          02:00:00               7.923179
..            ...               ...                    ...
188           4.0          22:00:00               9.250238
189           4.0          22:30:00              11.558966
190           4.0          23:00:00               7.146154
191           4.0          23:30:00               8.628148
192           5.0          17:30:00               0.000000

[193 rows x 3 columns]

## 15.Compute the difference of the average fare amount computed in the previous point with those computed at point 9.

In [263]:
diff = pd.merge(common_pay_int, payments_intervals, on=['clustered_pu_time', 'payment_type'])
diff['difference'] = diff['average fare amount 2'] - diff['average fare amount']
diff[['payment_type','clustered_pu_time','difference']]

     payment_type clustered_pu_time  difference
0             1.0          00:00:00   -5.325997
1             1.0          00:30:00   -4.837619
2             1.0          01:00:00   -4.349030
3             1.0          01:30:00   -4.394526
4             1.0          02:00:00   -4.085410
..            ...               ...         ...
188           4.0          22:00:00   -4.271443
189           4.0          22:30:00   -3.885056
190           4.0          23:00:00   -6.849109
191           4.0          23:30:00   -5.871349
192           5.0          17:30:00    0.000000

[193 rows x 3 columns]

## 16.Compute the ratio between the differences computed in the previous point and those computed in point 9. Note: you have to compute a ratio for each pair (payment type, interval).

In [269]:
diff['ratio'] = diff['difference']/diff['average fare amount']
diff[['payment_type','clustered_pu_time','ratio']]

     payment_type clustered_pu_time     ratio
0             1.0          00:00:00 -0.384018
1             1.0          00:30:00 -0.359068
2             1.0          01:00:00 -0.339116
3             1.0          01:30:00 -0.355602
4             1.0          02:00:00 -0.340207
..            ...               ...       ...
188           4.0          22:00:00 -0.315896
189           4.0          22:30:00 -0.251557
190           4.0          23:00:00 -0.489388
191           4.0          23:30:00 -0.404935
192           5.0          17:30:00       NaN

[193 rows x 3 columns]

## 17.Build chains of trips. Two trips are consecutive in a chain if (a) they have the same VendorID, (b) the pickup location of the second trip is also the dropoff location of the first trip, (c) the pickup time of the second trip is after the dropoff time of the first trip, and (d) the pickup time of the second trip is at most 2 minutes later than the dropoff time of the first trip.

In [47]:
from datetime import timedelta
import numpy as np
from collections import defaultdict, deque

In [48]:
df = prova.drop([ 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'payment_type', 'fare_amount',
                 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 
                 'congestion_surcharge', 'duration', 'pickup_interval','tip_ratio'], axis=1)
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,238,239
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,239,238
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,238,238
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,238,151
4,2.0,2020-01-01 00:01:58,2020-01-01 00:04:16,193,193
...,...,...,...,...,...
6339562,2.0,2020-01-31 23:38:07,2020-01-31 23:52:21,163,246
6339563,2.0,2020-01-31 23:00:18,2020-01-31 23:19:18,164,79
6339564,2.0,2020-01-31 23:24:22,2020-01-31 23:40:39,79,68
6339565,2.0,2020-01-31 23:44:22,2020-01-31 23:54:00,100,142
6339566,2.0,2020-01-31 23:19:37,2020-01-31 23:20:41,193,193

Hint: Add a column chain to the dataset. A chain can have more than two trips.

# Codice della Funzione

In [51]:
def identify_trip_chains1(df):
    
    df = df.sort_values(['VendorID', 'tpep_pickup_datetime']).reset_index(drop=True)
    df['chain'] = -1 

    time_threshold = pd.Timedelta(minutes=2)
    current_chain = 0

    
    for vendor_id, vendor_df in df.groupby('VendorID', sort=False):
        indices = vendor_df.index.values
        n = len(indices)
        pickup_times = vendor_df['tpep_pickup_datetime'].values
        dropoff_times = vendor_df['tpep_dropoff_datetime'].values
        PULocationIDs = vendor_df['PULocationID'].values
        DOLocationIDs = vendor_df['DOLocationID'].values
        chains = np.full(n, -1, dtype=int)

        active_chains = defaultdict(deque)
        chain_locations = {}

        for i in range(n):
            current_pickup = pickup_times[i]
            current_dropoff = dropoff_times[i]
            current_PULocationID = PULocationIDs[i]
            current_DOLocationID = DOLocationIDs[i]

            chain_list = active_chains[current_PULocationID]
            while chain_list and (current_pickup - chain_list[0][0]) > time_threshold:
                _, chain_id = chain_list.popleft()
                del chain_locations[chain_id]

            chain_found = False
            for idx, (dropoff_time, chain_id) in enumerate(chain_list):
                time_diff = current_pickup - dropoff_time
                if pd.Timedelta(0) < time_diff <= time_threshold:
                    chains[i] = chain_id
                    chain_found = True

                    chain_list.remove((dropoff_time, chain_id))
                    active_chains[current_DOLocationID].append((current_dropoff, chain_id))
                    chain_locations[chain_id] = (current_dropoff, current_DOLocationID)
                    break

            if not chain_found:
                current_chain += 1
                chains[i] = current_chain
                active_chains[current_DOLocationID].append((current_dropoff, current_chain))
                chain_locations[current_chain] = (current_dropoff, current_DOLocationID)

        df.loc[indices, 'chain'] = chains

    return df

###### Output VendorID = 1 (2'094'439 righe) (700 secondi 12 min) (864467 chain)

In [53]:
vendor1 = df[df['VendorID'] == 1]
vendor1

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID
0,1.0,2020-01-01 00:28:15,2020-01-01 00:33:03,238,239
1,1.0,2020-01-01 00:35:39,2020-01-01 00:43:04,239,238
2,1.0,2020-01-01 00:47:41,2020-01-01 00:53:52,238,238
3,1.0,2020-01-01 00:55:23,2020-01-01 01:00:14,238,151
9,1.0,2020-01-01 00:29:01,2020-01-01 00:40:28,246,48
...,...,...,...,...,...
6339543,1.0,2020-01-31 23:31:46,2020-01-31 23:41:29,100,233
6339544,1.0,2020-01-31 23:26:26,2020-01-31 23:48:26,79,48
6339550,1.0,2020-01-31 23:02:57,2020-01-31 23:15:20,230,236
6339551,1.0,2020-01-31 23:25:53,2020-01-31 23:35:44,237,140
6339552,1.0,2020-01-31 23:56:21,2020-02-01 00:09:46,161,7

In [54]:
vendor1_chains1 = identify_trip_chains1(vendor1)
vendor1_chains1.sort_values(['chain','tpep_pickup_datetime'])

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,chain
0,1.0,2020-01-01 00:00:00,2020-01-01 00:13:03,68,170,1
538,1.0,2020-01-01 00:13:28,2020-01-01 00:31:48,170,239,1
1871,1.0,2020-01-01 00:31:54,2020-01-01 01:42:07,239,25,1
7336,1.0,2020-01-01 01:43:32,2020-01-01 01:43:32,25,264,1
1,1.0,2020-01-01 00:00:03,2020-01-01 00:13:04,79,162,2
...,...,...,...,...,...,...
2094426,1.0,2020-01-31 23:59:43,2020-02-01 00:05:27,90,68,864463
2094433,1.0,2020-01-31 23:59:54,2020-02-01 00:05:56,256,232,864464
2094434,1.0,2020-01-31 23:59:54,2020-02-01 00:03:18,107,170,864465
2094437,1.0,2020-01-31 23:59:59,2020-02-01 00:40:07,79,61,864466
2094438,1.0,2020-01-31 23:59:59,2020-02-01 00:10:56,107,263,864467

# Output sample da 1'000'000 righe (1900 secondi 32 min) (648411 chain)

In [56]:
sample_df = df.sample(n=1000000)
sample_df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID
4829640,2.0,2020-01-25 00:19:05,2020-01-25 00:24:31,114,234
6275680,2.0,2020-01-31 19:22:48,2020-01-31 19:40:07,211,45
4663805,2.0,2020-01-24 11:31:05,2020-01-24 11:46:38,161,236
1089601,2.0,2020-01-07 11:22:28,2020-01-07 11:31:40,79,249
4503714,1.0,2020-01-23 17:38:53,2020-01-23 18:14:27,88,138
...,...,...,...,...,...
2686200,2.0,2020-01-14 20:21:46,2020-01-14 20:59:46,132,166
5221385,2.0,2020-01-26 21:55:52,2020-01-26 22:04:17,13,45
1221304,2.0,2020-01-07 22:31:19,2020-01-07 22:37:30,249,158
2534420,2.0,2020-01-14 08:35:22,2020-01-14 08:40:54,163,237
3971987,2.0,2020-01-21 09:58:01,2020-01-21 10:06:10,229,237

In [57]:
sample_df_chains = identify_trip_chains1(sample_df)
sample_df_chains.sort_values(['chain','tpep_pickup_datetime'])

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,PULocationID,DOLocationID,chain
0,1.0,2020-01-01 00:00:07,2020-01-01 00:03:26,75,75,1
1,1.0,2020-01-01 00:00:41,2020-01-01 00:16:23,90,4,2
2,1.0,2020-01-01 00:01:30,2020-01-01 00:07:32,42,152,3
3,1.0,2020-01-01 00:01:31,2020-01-01 00:10:24,263,41,4
4,1.0,2020-01-01 00:01:33,2020-01-01 00:28:57,132,71,5
...,...,...,...,...,...,...
999995,2.0,2020-02-01 00:15:23,2020-02-01 00:25:47,229,79,648407
999996,2.0,2020-05-07 10:44:29,2020-05-07 10:51:18,161,163,648408
999997,2.0,2020-07-10 10:46:19,2020-07-10 10:52:46,68,164,648409
999998,2.0,2020-07-10 11:25:13,2020-07-10 11:27:20,262,263,648410
999999,2.0,2020-07-10 11:34:11,2020-07-10 11:42:41,236,262,648411

# COMMENTO

In [59]:
def identify_trip_chains1(df):
    
    # Trova delle chain di viaggi a seconda che verifichino i seguenti vincoli:
    # a) il venditore è lo stesso 
    # b) la pickup location del secondo viaggio = drop off location del viaggio precedente
    # c) il pickup time del secondo viaggio deve essere successivo al drop off time del primo
    # d) il pickup time del secondo deve esssere max 2 minuti dopo il drop off time del primo
    
    # La funzione accetta come argomento il dataframe e restituisce il dataframe con l'aggiunta
    # della colonna chain
    
    
    # Prima si ordina il dataset per Vendor e Pickup time
    df = df.sort_values(['VendorID', 'tpep_pickup_datetime']).reset_index(drop=True)
    df['chain'] = -1  # Creazione nuova colonna 'chain' (il -1 indica che l'osservazione non appartiene a nessuna chain)

    time_threshold = pd.Timedelta(minutes=2) # la differenza di tempo massima tra i due trip 
    current_chain = 0 # inizio contatore per assegnare le chain

    # Si raggruppa per venditore (ciclo prima con tutti i vendor1 e poi tutti i vendor1, così da non 
    # controllare per i vendor 2 anche tutte le catene iniziate dai vendor1)
    for vendor_id, vendor_df in df.groupby('VendorID', sort=False): # sort = False perchè abbiamo già ordinato prima
        
        # Estraiamo le metriche necessarie per confrontare i viaggi come array tramite NumPy per ottimizzare i check
        indices = vendor_df.index.values
        n = len(indices)
        pickup_times = vendor_df['tpep_pickup_datetime'].values
        dropoff_times = vendor_df['tpep_dropoff_datetime'].values
        PULocationIDs = vendor_df['PULocationID'].values
        DOLocationIDs = vendor_df['DOLocationID'].values
        chains = np.full(n, -1, dtype=int) # array per memorizzare le chain (come la colonna chain, -1 indica che 
                                           # il trip non è stato assegnato ad una chain

        # Per ogni venditore, crea un dizionario dove le chiavi sono le Pickup location e i valori sono 'deque objects'
        # con dentro le info delle chain attive in quella location. (in pratica permette di controllare solo le chain con
        # la drop off location uguale alla pickup location)
        active_chains = defaultdict(deque)
        
        # Si crea un dizionario che ha come chiavi il numero della chain, e come valori le info sull'ultimo trip di 
        # quella chain. (in pratica, essendo i trip ordinati per pickup time, permetterà di eliminare le chain da 
        # prendere in considerazione se risultano più 'vecchie' di 2 minuti)
        chain_locations = {}

        # Per ogni trip, vengono estratte le metriche necessarie per confrontare l'i-esimo trip e le chain presenti in
        # active_chains
        for i in range(n):
            current_pickup = pickup_times[i]
            current_dropoff = dropoff_times[i]
            current_PULocationID = PULocationIDs[i]
            current_DOLocationID = DOLocationIDs[i]

            # Si comincia filtrando le chain che hanno come chiave (cioè drop off location) lo stesso valore della
            # pickup location del trip corrente (in questo modo si evita di controllare chain inutili)
            chain_list = active_chains[current_PULocationID]
            # Si continua rimuovendo le chain che hanno un drop off time troppo 'vecchio'
            while chain_list and (current_pickup - chain_list[0][0]) > time_threshold:
                # Estrae le chain_id delle chain 'vecchie' (.popleft() è fatto apposta per gli oggetti deques)
                _, chain_id = chain_list.popleft()
                # Si rimuove la chain dal dizionario
                del chain_locations[chain_id]

            # Si prova a cercare una chain valida per il trip corrente
            chain_found = False 
            # Si itera per tutte le chain recenti (time_diff <= minuti) con dropoff location = pickup location 
            # del trip corrente (enumerate prende anche l'index di chain_list che è la chain_id)
            for idx, (dropoff_time, chain_id) in enumerate(chain_list):
                time_diff = current_pickup - dropoff_time
                if pd.Timedelta(0) < time_diff <= time_diff:
                    # Se c'è un match allora si salva la chain_id
                    chains[i] = chain_id
                    chain_found = True

                    # Si rimuove la vecchia per aggiornare la chain
                    chain_list.remove((dropoff_time, chain_id))
                    # Si aggiorna il nuovo drop off time e la drop off location
                    active_chains[current_DOLocationID].append((current_dropoff, chain_id))
                    chain_locations[chain_id] = (current_dropoff, current_DOLocationID)
                    # Si chiude il loop appena aggiorna la chain
                    break  
            # Se non trova una chain, il trip corrente ne inizia una nuova
            if not chain_found:
                # Aggiorna il contatore per la chain_id
                current_chain += 1
                chains[i] = current_chain
                # Aggiunge la chain e le metriche per i confronti nei due dizionari
                active_chains[current_DOLocationID].append((current_dropoff, current_chain))
                chain_locations[current_chain] = (current_dropoff, current_DOLocationID)

        # L'array con le chain_id viene inserito nella colonna 'chain' del dataframe di partenza
        df.loc[indices, 'chain'] = chains

    return df